Site_Projet_py/Site_Projet_py/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect

def redirect_to_polls(request):
    return redirect('/polls/')


urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', redirect_to_polls),
]

Site_Projet_py/polls/urls.py
from django.urls import path
from .views import LobbyView
from . import views

app_name = "polls"
urlpatterns = [
    path("", LobbyView.as_view(), name='lobby'),
    path("test",views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),



    path("knn", views.index_p, name="knn"),
    path("page1", views.index_1, name="page1"),
    path("apply_Model", views.index_2, name="apply_Model"),


    path("proj",views.index_proj, name="proj"),
    path("code",views.code, name="code" )
]

Site_Projet_py/polls/models.py

from django.db import models
import datetime
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.question_text
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
        

        )

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=5) <= self.pub_date <= now




class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

Site_Projet_py/polls/views.py
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

from django.views.generic import TemplateView

class IndexView(generic.ListView):
    template_name = "template0.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
            :5
        ]

class LobbyView(TemplateView):
    template_name = "lobby.html"
    



class DetailView(generic.DetailView):
    model = Question
    template_name = "template1.html"
    def get_queryset(self):
       """
       Excludes any questions that aren't published yet.
       """
       return Question.objects.filter(pub_date__lte=timezone.now())



class ResultsView(generic.DetailView):
    model = Question
    template_name = "template2.html"

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "template1.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))



# PARTIE KNN ( de Safwan CHENDEB)
    

from django.http import HttpResponse
import pandas as pd

from django.template import loader

from django.shortcuts import render


import plotly.express as px

from  sklearn.neighbors import KNeighborsClassifier
from  sklearn.model_selection import train_test_split

#
from sklearn.cluster import KMeans




def index_p(request):
    data = pd.read_csv(r"C:\Users\aurel\Desktop\DATA_IRIS.txt", names=['sl','sw','pl','pw','label'])
    iris_classes=data.label.unique()
    #template = loader.get_template("template0.html")
    
    fig = px.scatter(data, x='pw',y='pl',color = 'label',size='sl',hover_data=['pw'])

    plot_html=fig.to_html(full_html=False,default_height=500,default_width=700 )

    context ={
        'les_labels_iris':iris_classes,
        'plot_html':plot_html
        }
    return render(request, "KNN/template0KNN.html", context)

def index_1(request):
    data = pd.read_csv(r"C:\Users\aurel\Desktop\DATA_IRIS.txt", names=['sl','sw','pl','pw','label'])
    iris_classes=data.label.unique()
    #template = loader.get_template("template0.html")
    
    fig = px.scatter(data, x='pw',y='pl',color = 'label',size='sl',hover_data=['pw'])

    plot_html=fig.to_html(full_html=False,default_height=500,default_width=700 )

    context ={
        'les_labels_iris':iris_classes,
        'plot_html':plot_html
        }
    return render(request, "KNN/template1KNN.html", context)

def KnnOnIris():
    data = pd.read_csv(r"C:\Users\aurel\Desktop\DATA_IRIS.txt", names=['sl', 'sw', 'pl', 'pw', 'label'])
    iris_classes = data.label.unique()
    data['label'].replace(
        iris_classes,
        [0, 1, 2],
        inplace=True
    )
    X = data.drop(columns=['label']).values
    y = data['label'].values
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    model = KNeighborsClassifier(n_neighbors=3) # création d'un modèle paramétré
    model.fit(X_train, y_train) # entraîner le modèle avec le dataset du training
    y_pred = model.predict(X_test)

    dataknn = pd.DataFrame(X_test, columns=['sl', 'sw', 'pl', 'pw'])
    dataknn['label'] = y_test
    dataknn['pred_label'] = y_pred
    fig = px.scatter(dataknn, x="pw", y="pl", color="label", size="pl", hover_data=['pw'], facet_col="pred_label")
    
    fig.update_layout(title="KNN Applied", xaxis_title="Petal Length", yaxis_title="Petal Width")
    plot_html = fig.to_html(full_html=False, default_height=500, default_width=700)
    return plot_html

def KMeansOnIris():
    data = pd.read_csv(r"C:\Users\aurel\Desktop\DATA_IRIS.txt", names=['sl', 'sw', 'pl', 'pw', 'label'])
    iris_classes = data.label.unique()
    data['label'].replace(
        iris_classes,
        [0, 1, 2],
        inplace=True
    )
    X = data.drop(columns=['label']).values
    y = data['label'].values
    model = KMeans(3, random_state=223)
    model.fit(X)
    pred_label = model.predict(X)
    data['pred_label'] = pred_label
    fig = px.scatter(data, x="pw", y="pl", color="label", 
                     size="pl", hover_data=['pw'], facet_col="pred_label")
    fig.update_layout(title="KMeans Applied", xaxis_title="Petal Length", yaxis_title="Petal Width")
    plot_html = fig.to_html(full_html=False, default_height=500, default_width=700)
    return plot_html




def index_2(request):
    template = loader.get_template('KNN/template1KNN.html')
    if(request.GET['model']=="KNN"):
        plot_html=KnnOnIris()
    if(request.GET['model']=="KMeans"):
        plot_html=KMeansOnIris




    context ={
        'plot_html':plot_html
        }
    return HttpResponse(template.render(context,request))




#Projet python


def index_proj(request):
    
    return render(request, "PROJ/temp_Projet.html")

def code(request):

    return render(request, "PROJ/temp_code.html")

def extraction_data():
    

    return 








































Site_Projet_py/polls/templates/KNN/template0KNN.html
<!doctype html>
<html >
  <head>
    <meta charset="utf-8" />
    <title>My test page</title>
  </head>   
  <body>
    <p>This is my page</p>
    {{les_labels_iris}}
  
  
    <ul>
    {% for a  in les_labels_iris %}
        <li>{{ a}}</li>
    {% endfor %}
    </ul>  
    

    <form action= "apply_Model">
    <label for="model-select">Choose a model:</label>
        <select name="model" id="model-select" onchange='if(this.values !=0){this.form.submit();}'>     
            <option value="0">--Please choose a model--</option>
            <option value="KNN">Knn</option>
            <option value="KMeans">KMeans</option>
        </select>
    </form>
 
    
  </body>
</html>

Site_Projet_py/polls/templates/KNN/template1KNN.html
<!doctype html>
<html >
  <head>
    <meta charset="utf-8" />
    <title>My test page</title>
  </head>   
  <body>
    <p>This is my page</p>
    {{les_labels_iris}}
  
  
    <ul>
    {% for a  in les_labels_iris %}
        <li>{{ a}}</li>
    {% endfor %}
    
    
    <form action="/polls" method="get">
    <button type="submit">Retour au lobby</button>
</form>
    
    </ul>  
    

    <form action= "apply_Model">
    <label for="model-select">Choose a model:</label>
        <select name="model" id="model-select" onchange='if(this.values !=0){this.form.submit();}'>     
            <option value="0">--Please choose a model--</option>
            <option value="KNN">Knn</option>
            <option value="KMeans">KMeans</option>
        </select>
    </form>
 
    {{plot_html|safe}}
    
  </body>
</html>

Site_Projet_py/polls/templates/PROJ/temp_Projet.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lobby</title>

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Affichage de code</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/styles/default.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/highlight.min.js"></script>
        <script>hljs.highlightAll();</script>
    </head>






</head>
<body>
    <h1>LE PROJET ULTIME</h1>
    <p> Description du projet....</p>
    <ul>
        <li><a href="{% url 'polls:lobby' %}">Revenir au lobby</a>


        <li><a href="{% url 'polls:code'%}">CODE</a>
        
    </ul>

    <iframe src="https://drive.google.com/file/d/1-jG54-mgFuZ1O_f_j3t2RwaMrXxBah-Z/preview" 
    width="600" height="800" 
    style="float: right; margin-left: 20px;">
</iframe>


<style>
    pre {
        background-color: #080000;
        padding: 10px;
        border-radius: 5px;
        overflow-x: auto;
    }
    code {
        font-family: "Courier New", monospace;
        color: #c7254e;
        background-color: #000408;
    }
</style>

<pre><code>
def hello():
    print("Hello, world!")
</code></pre>


</body>
</html>

Site_Projet_py/polls/templates/PROJ/temp_code.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lobby</title>

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Affichage de code</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/styles/default.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/highlight.min.js"></script>
        <script>hljs.highlightAll();</script>
    </head>






</head>
<body>
    <h1>LE PROJET ULTIME</h1>
    
    <ul>
        <form action="/polls" method="get">
            <button type="submit">Retour au lobby</button>

            <li><a href="{% url 'polls:index' %}">PAGE TEST</a></li>



        
    </ul>

    


<style>
    pre {
        background-color: #080000;
        padding: 10px;
        border-radius: 5px;
        overflow-x: auto;
    }
    code {
        font-family: "Courier New", monospace;
        color: #c7254e;
        background-color: #000408;
    }
</style>
<h2>Étapes pour installer Django</h2>
<ol>
    <li>Installer Python</li>
    <li>Installer Django avec la commande <code>pip install django</code></li>
    <li>Créer un projet Django avec <code>django-admin startproject myproject</code></li>
    <li>Lancer le serveur avec <code>python manage.py runserver</code></li>
    <li>Accéder à l'application sur <code>http://127.0.0.1:8000/</code></li>
</ol>

</body>
</html>

Site_Projet_py/polls/templates/lobby.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lobby</title>
</head>
<body>
    <h1>Bienvenue sur le site</h1>
    <p>Choisissez une section :</p>
    <ul>
        <li><a href="{% url 'polls:index' %}">PAGE TEST</a></li>
        <li><a href="{% url 'polls:knn' %}">Entraînement du S</a></li>

        <li><a href="{% url 'polls:proj' %}">Projet PYTHON A3</a></li>

        
    </ul>

    


<iframe width="300" height="170" 
    src="https://www.youtube.com/embed/MHZfJQYrJrk"
    title="YouTube video player" 
    frameborder="0" 
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
    allowfullscreen>
</iframe>

<li><a href="{% url 'admin:index' %}">Accès au Board Suprême XD</a></li>
<p>code admin</p>

    <ul> 
        <li>id: admin1</li>
        <li>mdp: admin1</li>
    </ul>
</body>
</html>

Site_Projet_py/polls/templates/template0.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">
<!doctype html>
<html >
  <head>
    <meta charset="utf-8" />
    <title>My test page</title>
  </head>
  <body>
  

    <p>
    
        {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>

    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}


    </p>
    <p>
    <a href="https://www.google.com">Lien vers Google</a>
      <br>
    <form action="/polls" method="get">
      <button type="submit">Retour au lobby</button>
    </p>
  </body>
</html>


Site_Projet_py/polls/templates/template1.html
<!doctype html>
<html >
  <head>
    <meta charset="utf-8" />
    <title>My test page</title>
  </head>
  <body>
  
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

<form action="/polls/test" method="get">
  <button type="submit">Retour a la page test</button>
  </body>
</html>





Site_Projet_py/polls/templates/template2.html
<!doctype html>
<html >
  <head>
    <meta charset="utf-8" />
    <title>My test page</title>
  </head>
  <body>
  
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a><br>
<a href="{% url 'polls:index' %}">Revenir au menu</a>
  </body>
</html>



